/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./supabase.schemas";
export type PublicApiKeyStatusEnum = z.infer<
  typeof generated.publicApiKeyStatusEnumSchema
>;
export type PublicPipelineResult = z.infer<
  typeof generated.publicPipelineResultSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicApiKeysRowSchema = z.infer<
  typeof generated.publicApiKeysRowSchemaSchema
>;
export type PublicApiKeysInsertSchema = z.infer<
  typeof generated.publicApiKeysInsertSchemaSchema
>;
export type PublicApiKeysUpdateSchema = z.infer<
  typeof generated.publicApiKeysUpdateSchemaSchema
>;
export type PublicApiKeysRelationshipsSchema = z.infer<
  typeof generated.publicApiKeysRelationshipsSchemaSchema
>;
export type PublicPipelineRunsRowSchema = z.infer<
  typeof generated.publicPipelineRunsRowSchemaSchema
>;
export type PublicPipelineRunsInsertSchema = z.infer<
  typeof generated.publicPipelineRunsInsertSchemaSchema
>;
export type PublicPipelineRunsUpdateSchema = z.infer<
  typeof generated.publicPipelineRunsUpdateSchemaSchema
>;
export type PublicPipelineRunsRelationshipsSchema = z.infer<
  typeof generated.publicPipelineRunsRelationshipsSchemaSchema
>;
export type PublicPipelinesRowSchema = z.infer<
  typeof generated.publicPipelinesRowSchemaSchema
>;
export type PublicPipelinesInsertSchema = z.infer<
  typeof generated.publicPipelinesInsertSchemaSchema
>;
export type PublicPipelinesUpdateSchema = z.infer<
  typeof generated.publicPipelinesUpdateSchemaSchema
>;
export type PublicPipelinesRelationshipsSchema = z.infer<
  typeof generated.publicPipelinesRelationshipsSchemaSchema
>;
export type PublicPromptLogsRowSchema = z.infer<
  typeof generated.publicPromptLogsRowSchemaSchema
>;
export type PublicPromptLogsInsertSchema = z.infer<
  typeof generated.publicPromptLogsInsertSchemaSchema
>;
export type PublicPromptLogsUpdateSchema = z.infer<
  typeof generated.publicPromptLogsUpdateSchemaSchema
>;
export type PublicPromptLogsRelationshipsSchema = z.infer<
  typeof generated.publicPromptLogsRelationshipsSchemaSchema
>;
export type PublicProvidersRowSchema = z.infer<
  typeof generated.publicProvidersRowSchemaSchema
>;
export type PublicProvidersInsertSchema = z.infer<
  typeof generated.publicProvidersInsertSchemaSchema
>;
export type PublicProvidersUpdateSchema = z.infer<
  typeof generated.publicProvidersUpdateSchemaSchema
>;
export type PublicProvidersRelationshipsSchema = z.infer<
  typeof generated.publicProvidersRelationshipsSchemaSchema
>;
export type PublicVirtualKeysRowSchema = z.infer<
  typeof generated.publicVirtualKeysRowSchemaSchema
>;
export type PublicVirtualKeysInsertSchema = z.infer<
  typeof generated.publicVirtualKeysInsertSchemaSchema
>;
export type PublicVirtualKeysUpdateSchema = z.infer<
  typeof generated.publicVirtualKeysUpdateSchemaSchema
>;
export type PublicVirtualKeysRelationshipsSchema = z.infer<
  typeof generated.publicVirtualKeysRelationshipsSchemaSchema
>;
export type PublicVOrphanedVirtualKeysRowSchema = z.infer<
  typeof generated.publicVOrphanedVirtualKeysRowSchemaSchema
>;
export type PublicVOrphanedVirtualKeysRelationshipsSchema = z.infer<
  typeof generated.publicVOrphanedVirtualKeysRelationshipsSchemaSchema
>;
export type PublicVPipelineStatsTotalRowSchema = z.infer<
  typeof generated.publicVPipelineStatsTotalRowSchemaSchema
>;
export type PublicVPipelineStatsTotalRelationshipsSchema = z.infer<
  typeof generated.publicVPipelineStatsTotalRelationshipsSchemaSchema
>;
